// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJylIorCP2jE6tWM2bDDsiMQ5flIPCoo',
    appId: '1:150219738865:web:19f0180914e4230dafe350',
    messagingSenderId: '150219738865',
    projectId: 'liferpg-or',
    authDomain: 'liferpg-or.firebaseapp.com',
    storageBucket: 'liferpg-or.firebasestorage.app',
    measurementId: 'G-786GW63YY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJylIorCP2jE6tWM2bDDsiMQ5flIPCoo',
    appId:
        '1:150219738865:android:c898c0b70e28f307afe350', // Note: This is a placeholder, usually generated by CLI
    messagingSenderId: '150219738865',
    projectId: 'liferpg-or',
    storageBucket: 'liferpg-or.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJylIorCP2jE6tWM2bDDsiMQ5flIPCoo',
    appId:
        '1:150219738865:ios:b3e4f3a7f8e9d0c1b2a3d4', // Note: This is a placeholder, usually generated by CLI
    messagingSenderId: '150219738865',
    projectId: 'liferpg-or',
    storageBucket: 'liferpg-or.firebasestorage.app',
    iosBundleId: 'com.example.rpgOverride1v0',
  );
}
